module.exports = {
abilities: require(__dirname + '/build/abilities.json'),
ability_ids: require(__dirname + '/build/ability_ids.json'),
ability_keys: require(__dirname + '/build/ability_keys.json'),
build: require(__dirname + '/build/build.json'),
check-versions: require(__dirname + '/build/check-versions.json'),
cluster: require(__dirname + '/build/cluster.json'),
countries: require(__dirname + '/build/countries.json'),
dev-client: require(__dirname + '/build/dev-client.json'),
dev-server: require(__dirname + '/build/dev-server.json'),
hero_names: require(__dirname + '/build/hero_names.json'),
heroes: require(__dirname + '/build/heroes.json'),
item_groups: require(__dirname + '/build/item_groups.json'),
item_ids: require(__dirname + '/build/item_ids.json'),
region: require(__dirname + '/build/region.json'),
update-data: require(__dirname + '/build/update-data.json'),
utils: require(__dirname + '/build/utils.json'),
vue-loader: require(__dirname + '/build/vue-loader.json'),
webpack: require(__dirname + '/build/webpack.json'),
webpack: require(__dirname + '/build/webpack.json'),
webpack: require(__dirname + '/build/webpack.json')
};